[package]
name = "gurufocus_api"
version = "0.3.0"
authors = ["Mark Beinker <mwb@quantlink.de>"]
edition = "2018"
description = "A rust adapter to the GuruFocus API, a provider of financial data."
license = "MIT OR Apache-2.0"
repository = "https://github.com/xemwebe/gurufocus_api"
readme = "README.md"

[dependencies]
reqwest = "0.9.22"
serde_json = "1.0"
chrono = "0.4.9"
serde = { version = "1.0", features = ["derive"] }
